### ISSUE TITLE
Getting java.lang.NoSuchMethodError with jolokia-jvm-1.6.2-agent.jar during startup

### ISSUE THREAD

**Issue by skarsaune** [jolokia/jolokia#454]
Context: Running -javaagent:jolokia-jvm-1.6.2-agent.jar 

Getting this during startup with jolokia-jvm-1.6.2-agent.jar
Exception in thread "JolokiaStart" java.lang.NoSuchMethodError: 'void org.jolokia.discovery.DiscoveryMulticastResponder.<init>(org.jolokia.discovery.AgentDetailsHolder, org.jolokia.restrictor.Restrictor, org.jolokia.util.LogHandler)'
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.start(JolokiaHttpHandler.java:111)
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.start(JolokiaHttpHandler.java:142)
	at org.jolokia.jvmagent.JolokiaServer.start(JolokiaServer.java:107)
	at org.jolokia.jvmagent.JvmAgent$1.run(JvmAgent.java:100)

Wondering whether it could be JVM specific?

Never mind: got it to work with jolokia-jvm-1.6.3-SNAPSHOT-agent.jar again, wondering if I picked the wrong jar before.
